import { ActionConfig, CategoryConfig, ResourceConfig, TaskConfig, ItemConfig, SlotConfig } from "../types";

export const CATEGORIES: CategoryConfig[] = [
  { id: "wellness", name: "Wellness - Body Practices" },
];

export const RESOURCES: ResourceConfig[] = [];

export const SLOTS: SlotConfig[] = [
  {
    id: "accessory_2",
    name: "Accessory II",
    prerequisites: [],
    prerequisitesAny: [
      { actionId: "wellness_stitch_pouch_yoga", minExecutions: 1 },
      { actionId: "wellness_stitch_pouch_running", minExecutions: 1 },
      { actionId: "wellness_stitch_pouch_swimming", minExecutions: 1 },
      { actionId: "wellness_stitch_pouch_hiking", minExecutions: 1 },
    ],
  },
];

export const TASKS: TaskConfig[] = [
  {
    id: "rest_yoga",
    name: "Yoga Flow",
    description: "Held breaths, slow transitions. Mana gathers like heat.",
    category: "wellness",
    type: "rest",
    progressRequired: 1,
    autoRestart: true,
    costPerSecond: [],
    effectsPerSecond: [
      { type: "add_resource", resourceId: "time", amount: 0.6, scaleFactor: 0.02, scaleType: "fixed" },
      { type: "add_resource", resourceId: "health", amount: 0.4, scaleFactor: 0.02, scaleType: "fixed" },
      { type: "add_resource", resourceId: "mana", amount: 0.7, scaleFactor: 0.04, scaleType: "fixed" },
    ],
    prerequisites: [{ actionId: "wellness_choose_yoga", minExecutions: 1 }],
    xpPerSecond: 6,
  },
  {
    id: "rest_running",
    name: "Street Run",
    description: "Counterclockwise loops. Time stretches when you chase it.",
    category: "wellness",
    type: "rest",
    progressRequired: 1,
    autoRestart: true,
    costPerSecond: [],
    effectsPerSecond: [
      { type: "add_resource", resourceId: "time", amount: 1.1, scaleFactor: 0.05, scaleType: "fixed" },
      { type: "add_resource", resourceId: "health", amount: 0.6, scaleFactor: 0.03, scaleType: "fixed" },
      { type: "add_resource", resourceId: "mana", amount: 0.15, scaleFactor: 0.01, scaleType: "fixed" },
    ],
    prerequisites: [{ actionId: "wellness_choose_running", minExecutions: 1 }],
    xpPerSecond: 6,
  },
  {
    id: "rest_swimming",
    name: "Lap Swimming",
    description: "Two lengths, breathe, turn. Health steadies.",
    category: "wellness",
    type: "rest",
    progressRequired: 1,
    autoRestart: true,
    costPerSecond: [],
    effectsPerSecond: [
      { type: "add_resource", resourceId: "time", amount: 0.7, scaleFactor: 0.03, scaleType: "fixed" },
      { type: "add_resource", resourceId: "health", amount: 0.7, scaleFactor: 0.04, scaleType: "fixed" },
      { type: "add_resource", resourceId: "mana", amount: 0.4, scaleFactor: 0.02, scaleType: "fixed" },
    ],
    prerequisites: [{ actionId: "wellness_choose_swimming", minExecutions: 1 }],
    xpPerSecond: 6,
  },
  {
    id: "rest_hiking",
    name: "Trail Hike",
    description: "Elevation and quiet. Time pays you back with spare change found on trails.",
    category: "wellness",
    type: "rest",
    progressRequired: 1,
    autoRestart: true,
    costPerSecond: [],
    effectsPerSecond: [
      { type: "add_resource", resourceId: "time", amount: 0.9, scaleFactor: 0.04, scaleType: "fixed" },
      { type: "add_resource", resourceId: "health", amount: 0.5, scaleFactor: 0.02, scaleType: "fixed" },
      { type: "add_resource", resourceId: "mana", amount: 0.3, scaleFactor: 0.02, scaleType: "fixed" },
      { type: "add_resource", resourceId: "money", amount: 0.05, scaleFactor: 0.01, scaleType: "fixed" },
    ],
    prerequisites: [{ actionId: "wellness_choose_hiking", minExecutions: 1 }],
    xpPerSecond: 6,
  },
];
export const ACTIONS: ActionConfig[] = [
  {
    id: "wellness_find_flyer",
    name: "Find Wellness Flyer",
    description: "Tucked under your bench: 'Free trial — yoga, running, swimming, hiking. Learn to rest on purpose.' The paper smells faintly of cedar.",
    category: "wellness",
    costs: [],
    effects: [{ type: "modify_max_resource_flat", resourceId: "mana", amount: 3 }],
    prerequisites: [{ actionId: "appartment", minExecutions: 1 }, { taskId: "rest_bench", minLevel: 2 }],
    maxExecutions: 1,
    logMessage: "A flyer flutters. Four paths to rest."
  },
  {
    id: "wellness_choose_yoga",
    name: "Enroll: Yoga",
    description: "Slow breath, held shapes. You learn where you hold tension and how to put it down.",
    category: "wellness",
    costs: [{ resourceId: "money", amount: 25 }],
    effects: [],
    prerequisites: [{ actionId: "wellness_find_flyer", minExecutions: 1 }],
    maxExecutions: 1,
    exclusiveWith: ["wellness_choose_running","wellness_choose_swimming","wellness_choose_hiking"],
    locks: ["wellness_choose_running","wellness_choose_swimming","wellness_choose_hiking","rest_running","rest_swimming","rest_hiking"],
    lockDescription: "Choosing Yoga closes Running, Swimming, Hiking.",
    logMessage: "You sign for yoga. The other flyers fade."
  },
  {
    id: "wellness_choose_running",
    name: "Enroll: Running",
    description: "Pavement, breath, rhythm. The city becomes a loop you can master.",
    category: "wellness",
    costs: [{ resourceId: "money", amount: 25 }],
    effects: [],
    prerequisites: [{ actionId: "wellness_find_flyer", minExecutions: 1 }],
    maxExecutions: 1,
    exclusiveWith: ["wellness_choose_yoga","wellness_choose_swimming","wellness_choose_hiking"],
    locks: ["wellness_choose_yoga","wellness_choose_swimming","wellness_choose_hiking","rest_yoga","rest_swimming","rest_hiking"],
    lockDescription: "Choosing Running closes others.",
    logMessage: "You lace up. The mat and pool can wait."
  },
  {
    id: "wellness_choose_swimming",
    name: "Enroll: Swimming",
    description: "Water holds you without asking. You count strokes and forget to count problems.",
    category: "wellness",
    costs: [{ resourceId: "money", amount: 25 }],
    effects: [],
    prerequisites: [{ actionId: "wellness_find_flyer", minExecutions: 1 }],
    maxExecutions: 1,
    exclusiveWith: ["wellness_choose_yoga","wellness_choose_running","wellness_choose_hiking"],
    locks: ["wellness_choose_yoga","wellness_choose_running","wellness_choose_hiking","rest_yoga","rest_running","rest_hiking"],
    lockDescription: "Choosing Swimming closes others.",
    logMessage: "Chlorine and quiet. You choose the pool."
  },
  {
    id: "wellness_choose_hiking",
    name: "Enroll: Hiking",
    description: "Dirt, incline, sky. Time dilates at altitude.",
    category: "wellness",
    costs: [{ resourceId: "money", amount: 25 }],
    effects: [],
    prerequisites: [{ actionId: "wellness_find_flyer", minExecutions: 1 }],
    maxExecutions: 1,
    exclusiveWith: ["wellness_choose_yoga","wellness_choose_running","wellness_choose_swimming"],
    locks: ["wellness_choose_yoga","wellness_choose_running","wellness_choose_swimming","rest_yoga","rest_running","rest_swimming"],
    lockDescription: "Choosing Hiking closes others.",
    logMessage: "You pick the trail. The map is already creased."
  },
  {
    id: "wellness_stitch_pouch_yoga",
    name: "Stitch Second Pouch (Yoga)",
    description: "You sew a second pocket onto your bag. It takes time, money, and the discipline you learned from yoga.",
    category: "wellness",
    costs: [{ resourceId: "money", amount: 80 }, { resourceId: "mana", amount: 15 }],
    effects: [{ type: "modify_max_resource_flat", resourceId: "health", amount: 4 }],
    prerequisites: [{ actionId: "wellness_find_flyer", minExecutions: 1 }, { taskId: "rest_yoga", minLevel: 3 }],
    maxExecutions: 1,
    exclusiveWith: ["wellness_stitch_pouch_running", "wellness_stitch_pouch_swimming", "wellness_stitch_pouch_hiking"],
    logMessage: "Your bag now holds two charms. The second pouch hangs light. (Yoga discipline)"
  },
  {
    id: "wellness_stitch_pouch_running",
    name: "Stitch Second Pouch (Running)",
    description: "You sew a second pocket onto your bag. It takes time, money, and the discipline you learned from running.",
    category: "wellness",
    costs: [{ resourceId: "money", amount: 80 }, { resourceId: "mana", amount: 15 }],
    effects: [{ type: "modify_max_resource_flat", resourceId: "health", amount: 4 }],
    prerequisites: [{ actionId: "wellness_find_flyer", minExecutions: 1 }, { taskId: "rest_running", minLevel: 3 }],
    maxExecutions: 1,
    exclusiveWith: ["wellness_stitch_pouch_yoga", "wellness_stitch_pouch_swimming", "wellness_stitch_pouch_hiking"],
    logMessage: "Your bag now holds two charms. The second pouch hangs light. (Running discipline)"
  },
  {
    id: "wellness_stitch_pouch_swimming",
    name: "Stitch Second Pouch (Swimming)",
    description: "You sew a second pocket onto your bag. It takes time, money, and the discipline you learned from swimming.",
    category: "wellness",
    costs: [{ resourceId: "money", amount: 80 }, { resourceId: "mana", amount: 15 }],
    effects: [{ type: "modify_max_resource_flat", resourceId: "health", amount: 4 }],
    prerequisites: [{ actionId: "wellness_find_flyer", minExecutions: 1 }, { taskId: "rest_swimming", minLevel: 3 }],
    maxExecutions: 1,
    exclusiveWith: ["wellness_stitch_pouch_yoga", "wellness_stitch_pouch_running", "wellness_stitch_pouch_hiking"],
    logMessage: "Your bag now holds two charms. The second pouch hangs light. (Swimming discipline)"
  },
  {
    id: "wellness_stitch_pouch_hiking",
    name: "Stitch Second Pouch (Hiking)",
    description: "You sew a second pocket onto your bag. It takes time, money, and the discipline you learned from hiking.",
    category: "wellness",
    costs: [{ resourceId: "money", amount: 80 }, { resourceId: "mana", amount: 15 }],
    effects: [{ type: "modify_max_resource_flat", resourceId: "health", amount: 4 }],
    prerequisites: [{ actionId: "wellness_find_flyer", minExecutions: 1 }, { taskId: "rest_hiking", minLevel: 3 }],
    maxExecutions: 1,
    exclusiveWith: ["wellness_stitch_pouch_yoga", "wellness_stitch_pouch_running", "wellness_stitch_pouch_swimming"],
    logMessage: "Your bag now holds two charms. The second pouch hangs light. (Hiking discipline)"
  },
  {
    id: "wellness_claim_yoga_mat",
    name: "Claim Yoga Mat",
    description: "The studio gifts you a mat.",
    category: "wellness",
    costs: [],
    effects: [{ type: "add_item", itemId: "yoga_mat", amount: 1 }, { type: "modify_max_resource_flat", resourceId: "health", amount: 4 }],
    prerequisites: [{ taskId: "rest_yoga", minLevel: 3 }],
    maxExecutions: 1,
    logMessage: "You unroll the mat. It remembers your shape."
  },
  {
    id: "wellness_master_yoga",
    name: "Master the Breath",
    description: "Inhale four, hold four, exhale six. The room thins.",
    category: "wellness",
    costs: [{ resourceId: "mana", amount: 20 }],
    effects: [{ type: "modify_passive_gen", resourceId: "mana", amount: 0.06 }, { type: "add_item", itemId: "yoga_bracelet", amount: 1 }],
    prerequisites: [{ taskId: "rest_yoga", minLevel: 5 }],
    maxExecutions: 1,
    logMessage: "Your breath steadies the room."
  },
  {
    id: "wellness_claim_trail_shoes",
    name: "Claim Trail Shoes",
    description: "The running shop slides you a pair, broken in just enough.",
    category: "wellness",
    costs: [],
    effects: [{ type: "add_item", itemId: "trail_shoes", amount: 1 }, { type: "modify_max_resource_flat", resourceId: "health", amount: 4 }],
    prerequisites: [{ taskId: "rest_running", minLevel: 3 }],
    maxExecutions: 1,
    logMessage: "New tread, old streets."
  },
  {
    id: "wellness_master_running",
    name: "Master the Pace",
    description: "You find the rhythm where effort disappears.",
    category: "wellness",
    costs: [{ resourceId: "mana", amount: 20 }],
    effects: [{ type: "modify_passive_gen", resourceId: "time", amount: 0.05 }, { type: "add_item", itemId: "race_bib", amount: 1 }],
    prerequisites: [{ taskId: "rest_running", minLevel: 5 }],
    maxExecutions: 1,
    logMessage: "Race day never ends."
  },
  {
    id: "wellness_claim_swim_goggles",
    name: "Claim Swim Goggles",
    description: "A spare pair from the lost-and-found, now yours.",
    category: "wellness",
    costs: [],
    effects: [{ type: "add_item", itemId: "swim_goggles", amount: 1 }, { type: "modify_max_resource_flat", resourceId: "health", amount: 4 }],
    prerequisites: [{ taskId: "rest_swimming", minLevel: 3 }],
    maxExecutions: 1,
    logMessage: "The lenses clear."
  },
  {
    id: "wellness_master_swimming",
    name: "Master the Stroke",
    description: "Water parts exactly as you intend.",
    category: "wellness",
    costs: [{ resourceId: "mana", amount: 20 }],
    effects: [{ type: "modify_passive_gen", resourceId: "health", amount: 0.06 }, { type: "add_item", itemId: "pool_key", amount: 1 }],
    prerequisites: [{ taskId: "rest_swimming", minLevel: 5 }],
    maxExecutions: 1,
    logMessage: "The pool is yours after hours."
  },
  {
    id: "wellness_claim_trekking_poles",
    name: "Claim Trekking Poles",
    description: "Carbon, cork grips, a little too long until you adjust them.",
    category: "wellness",
    costs: [],
    effects: [{ type: "add_item", itemId: "trekking_poles", amount: 1 }, { type: "modify_max_resource_flat", resourceId: "health", amount: 4 }],
    prerequisites: [{ taskId: "rest_hiking", minLevel: 3 }],
    maxExecutions: 1,
    logMessage: "Click-clack, up the trail."
  },
  {
    id: "wellness_master_hiking",
    name: "Master the Ascent",
    description: "The summit is not the point. You go anyway.",
    category: "wellness",
    costs: [{ resourceId: "mana", amount: 20 }],
    effects: [{ type: "modify_passive_gen", resourceId: "mana", amount: 0.04 }, { type: "add_item", itemId: "summit_patch", amount: 1 }],
    prerequisites: [{ taskId: "rest_hiking", minLevel: 5 }],
    maxExecutions: 1,
    logMessage: "You sew the patch on."
  },
];
export const ITEMS: ItemConfig[] = [
  { id: "yoga_mat", name: "Woven Yoga Mat", description: "Slightly indented where you kneel. Smells of cedar.", slot: "accessory", effects: [{ type: "modify_passive_gen", resourceId: "mana", amount: 0.08 }] },
  { id: "yoga_bracelet", name: "Breath Beads", description: "Wooden beads, worn smooth.", slot: "accessory_2", effects: [{ type: "modify_passive_gen", resourceId: "mana", amount: 0.04 }, { type: "modify_max_resource_flat", resourceId: "health", amount: 6 }] },
  { id: "trail_shoes", name: "Trail Shoes", description: "Mud in the tread even after cleaning.", slot: "accessory", effects: [{ type: "modify_yield_pct", taskId: "rest_running", amount: 0.12 }] },
  { id: "race_bib", name: "Race Bib #204", description: "You kept it. You earned the number.", slot: "accessory_2", effects: [{ type: "modify_max_resource_flat", resourceId: "time", amount: 3 }] },
  { id: "swim_goggles", name: "Fogged Goggles", description: "You see better with them off, somehow.", slot: "accessory", effects: [{ type: "modify_max_resource_flat", resourceId: "health", amount: 6 }] },
  { id: "pool_key", name: "Pool Key", description: "After-hours access, unofficially.", slot: "accessory_2", effects: [{ type: "modify_passive_gen", resourceId: "health", amount: 0.03 }] },
  { id: "trekking_poles", name: "Trekking Poles", description: "Click-clack on stone.", slot: "accessory", effects: [{ type: "modify_yield_pct", taskId: "rest_hiking", amount: 0.15 }] },
  { id: "summit_patch", name: "Summit Patch", description: "Sew it on. You were there.", slot: "accessory_2", effects: [{ type: "modify_max_resource_flat", resourceId: "mana", amount: 7 }] },
];
