import { ActionConfig } from "../../types";

export const ACTIONS: ActionConfig[] = [
  {
    id: "first_spark",
    name: "The First Spark",
    description: "Millhollow dusk — the Sundering's light gathers without asking. A brief, bright, uncontrolled spark. Prologue: it leaves ash on your hands and emptiness in your reserve. Click to let it happen.",
    category: "chapter1",
    costs: [],
    effects: [],
    firstCompletionEffects: [{ type: "set_flag", flagId: "first_spark", amount: 1 }],
    maxExecutions: 1,
    hideWhenComplete: true,
    logMessage: "Heat. Light. Then ash on your hands. The air still smells of ozone.",
  },
  {
    id: "cast_ash",
    name: "Cast: Coax the Ember",
    description: "Grow or shrink an existing flame. Introductory Ash casting. The first Aspect Widow Cathal told you to try.",
    category: "ash",
    spellId: "coax_the_ember",
    costs: [],
    effects: [],
    cooldownMs: 2000,
    prerequisites: [{ taskId: "catch_your_breath", minExecutions: 1 }],
    logMessage: "The ember leans toward your intent, obedient for once.",
  },
  {
    id: "cast_root",
    name: "Cast: Nudge the Root",
    description: "Grow a small plant, once. Introductory Root casting — unlocked after Ash answers a few times.",
    category: "root",
    spellId: "nudge_the_root",
    costs: [],
    effects: [],
    cooldownMs: 3000,
    prerequisites: [{ actionId: "cast_ash", minExecutions: 3 }],
    logMessage: "A seed splits. Something green considers the light.",
  },
  {
    id: "cast_hush",
    name: "Cast: Quiet the Bell",
    description: "Mute a small sound source briefly. Introductory Hush casting — unlocked after Root steadies.",
    category: "hush",
    spellId: "quiet_the_bell",
    costs: [],
    effects: [],
    cooldownMs: 1500,
    prerequisites: [{ actionId: "cast_root", minExecutions: 3 }],
    logMessage: "The bell swings — silently. It looks almost offended.",
  },
  {
    id: "mote_conversion_i",
    name: "Condense Motes to Mana",
    description: "Press loose Motes back into your reserve. Crude, but it works. You notice it only after you've shaken loose enough residue.",
    category: "chapter1",
    costs: [{ resourceId: "motes", amount: 10 }],
    effects: [{ type: "add_resource", resourceId: "mana", amount: 5 }],
    cooldownMs: 1000,
    prerequisites: [{ actionId: "cast_ash", minExecutions: 2 }],
    logMessage: "The motes fold into blue light.",
  },
  {
    id: "widow_cathal_visit",
    name: "Visit Widow Cathal",
    description: "She recognizes what's happening to you before you do. After a few clean casts, she knows you're ready to hear more. She sends you toward Hollow Reach.",
    category: "chapter1",
    costs: [],
    effects: [],
    firstCompletionEffects: [
      { type: "modify_max_resource_flat", resourceId: "mana", amount: 18 },
      { type: "add_resource", resourceId: "mana", amount: 18 },
      { type: "set_flag", flagId: "met_cathal", amount: 1 },
    ],
    maxExecutions: 1,
    prerequisites: [{ actionId: "cast_ash", minExecutions: 4 }],
    logMessage: "\"You will be told the Sundering is a wound,\" she says. \"It is. That's not all it is.\"",
    hideWhenComplete: true,
  },
];
