import { ActionConfig } from "../../types";

export const ACTIONS: ActionConfig[] = [
  {
    id: "cast_ash",
    name: "Cast: Coax the Ember",
    description: "Grow or shrink an existing flame. Introductory Ash casting.",
    category: "ash",
    spellId: "coax_the_ember",
    costs: [],
    effects: [],
    maxExecutions: 999999,
    cooldownMs: 2000,
    prerequisites: [{ taskId: "catch_your_breath", minExecutions: 1 }],
    logMessage: "The ember leans toward your intent, obedient for once.",
  },
  {
    id: "cast_root",
    name: "Cast: Nudge the Root",
    description: "Grow a small plant, once. Introductory Root casting.",
    category: "root",
    spellId: "nudge_the_root",
    costs: [],
    effects: [],
    maxExecutions: 999999,
    cooldownMs: 3000,
    prerequisites: [{ taskId: "catch_your_breath", minExecutions: 1 }],
    logMessage: "A seed splits. Something green considers the light.",
  },
  {
    id: "cast_hush",
    name: "Cast: Quiet the Bell",
    description: "Mute a small sound source briefly. Introductory Hush casting.",
    category: "hush",
    spellId: "quiet_the_bell",
    costs: [],
    effects: [],
    maxExecutions: 999999,
    cooldownMs: 1500,
    prerequisites: [{ taskId: "catch_your_breath", minExecutions: 1 }],
    logMessage: "The bell swings — silently. It looks almost offended.",
  },
  {
    id: "mote_conversion_i",
    name: "Condense Motes to Mana",
    description: "Press loose Motes back into your reserve. Crude, but it works.",
    category: "chapter1",
    costs: [{ resourceId: "motes", amount: 10 }],
    effects: [{ type: "add_resource", resourceId: "mana", amount: 5 }],
    maxExecutions: 999999,
    cooldownMs: 1000,
    prerequisites: [{ taskId: "catch_your_breath", minExecutions: 1 }],
    logMessage: "The motes fold into blue light.",
  },
  {
    id: "widow_cathal_visit",
    name: "Visit Widow Cathal",
    description: "She recognizes what's happening to you before you do. She sends you toward Hollow Reach.",
    category: "chapter1",
    costs: [],
    effects: [],
    firstCompletionEffects: [
      { type: "modify_max_resource_flat", resourceId: "mana", amount: 25 },
      { type: "add_resource", resourceId: "mana", amount: 25 },
      { type: "set_flag", flagId: "met_cathal", amount: 1 },
    ],
    maxExecutions: 1,
    prerequisites: [{ taskId: "catch_your_breath", minExecutions: 1 }],
    logMessage: "\"You will be told the Sundering is a wound,\" she says. \"It is. That's not all it is.\"",
    hideWhenComplete: true,
  },
];
