import { TaskConfig } from "../../types";

export const TASKS: TaskConfig[] = [
  {
    id: "catch_your_breath",
    name: "Catch Your Breath",
    description: "The spark still crackles under your skin. Calming down - not casting harder - is the way through. You did not mean to cast; now you must learn to steady.",
    category: "chapter1",
    progressRequired: 3,
    maxExecutions: 3,
    hideWhenComplete: false,
    costPerSecond: [],
    effectsPerSecond: [],
    completionEffects: [
      { type: "modify_max_resource_flat", resourceId: "focus", amount: 2 },
      { type: "add_resource", resourceId: "focus", amount: 2 },
      { type: "modify_max_resource_flat", resourceId: "mana", amount: 5 },
      { type: "add_resource", resourceId: "mana", amount: 2 }
    ],
    firstCompletionEffects: [
      { type: "add_item", itemId: "millers_charm", amount: 1 },
    ],
    prerequisites: [{ actionId: "first_spark", minExecutions: 1 }],
  },
  {
    id: "ember_practice",
    name: "Ember Practice",
    description: "Coax a candle flame taller and shorter. Ash is greedy - high cost, bursty yield. Burns Focus fast for more Motes.",
    category: "chapter1",
    progressRequired: 5,
    autoRestart: true,
    costPerSecond: [{ resourceId: "focus", amount: 0.5 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 0.6 }],
    xpPerSecond: 6,
    prerequisites: [{ taskId: "catch_your_breath", minExecutions: 3 }],
  },
  {
    id: "hedge_practice",
    name: "Hedge Practice",
    description: "Encourage a hedge to grow half an inch and stop. Root is patient - cheap and steady, lower yield but you can hold it longer.",
    category: "chapter1",
    progressRequired: 5,
    autoRestart: true,
    costPerSecond: [{ resourceId: "focus", amount: 0.2 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 0.35 }],
    xpPerSecond: 4,
    prerequisites: [{ actionId: "cast_ash", minExecutions: 3 }],
  },
  {
    id: "stillness_practice",
    name: "Stillness Practice",
    description: "Silence a ringing bell early. Hush is in-between - moderate cost, moderate yield, but steadies your rhythm.",
    category: "chapter1",
    progressRequired: 5,
    autoRestart: true,
    costPerSecond: [{ resourceId: "focus", amount: 0.35 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 0.5 }],
    xpPerSecond: 5,
    prerequisites: [{ actionId: "cast_root", minExecutions: 3 }],
  },
  {
    id: "errand_running",
    name: "Errand Running",
    description: "Non-magical village chores that quietly build Focus through routine. After you’ve steadied from the first spark, routine steadies what practice cannot.",
    category: "chapter1",
    type: "rest",
    costPerSecond: [],
    effectsPerSecond: [{ type: "add_resource", resourceId: "focus", amount: 0.25 }],
    xpPerSecond: 1,
    prerequisites: [{ taskId: "catch_your_breath", minExecutions: 3 }],
  },
];
