import { ActionConfig } from "../../types";

export const ACTIONS: ActionConfig[] = [
  // Undercroft seal / Braidstone Ring acquisition - gates braided casting outside Undercroft
  {
    id: "acquire_braidstone_ring",
    name: "Break the Undercroft Seal",
    description: "Behind a braid-only lock, Year 74. Claim the Braidstone Ring to weave braids outside the flooded Undercroft.",
    category: "chapter3",
    costs: [
      { resourceId: "skyglass", amount: 8 },
      { resourceId: "motes", amount: 30 },
    ],
    effects: [],
    firstCompletionEffects: [
      { type: "add_item", itemId: "braidstone_ring", amount: 1 },
      { type: "set_flag", flagId: "undercroft_seal_opened", amount: 1 },
      { type: "set_flag", flagId: "braidstone_ring_acquired", amount: 1 },
    ],
    maxExecutions: 1,
    prerequisites: [
      { actionId: "skyglass_unlock", minExecutions: 1 },
      { taskId: "braid_practice", minExecutions: 1 },
    ],
    logMessage: "The seal gives with a sigh. The ring is warm, threaded with two colors at once.",
  },

  // Braid castings - gated behind acquire_braidstone_ring (itemId prereq unavailable, use actionId)
  {
    id: "cast_smolder",
    name: "Weave Smolder",
    description: "A burn with no light and no sound. Ash + Hush braid (The Slow Ember).",
    category: "smolder",
    spellId: "cast_smolder",
    costs: [],
    effects: [],
    cooldownMs: 6000,
    prerequisites: [{ actionId: "acquire_braidstone_ring", minExecutions: 1 }],
    logMessage: "Smolder takes - quietly, completely.",
  },
  {
    id: "cast_dormancy",
    name: "Weave Dormancy",
    description: "Silence laid over growth. Hush + Root braid (The Held Season).",
    category: "dormancy",
    spellId: "cast_dormancy",
    costs: [],
    effects: [],
    cooldownMs: 7000,
    prerequisites: [{ actionId: "acquire_braidstone_ring", minExecutions: 1 }],
    logMessage: "Growth pauses mid-breath. Nothing ages while Dormancy holds.",
  },
  {
    id: "cast_heartwood",
    name: "Weave Heartwood",
    description: "Living growth made permanent. Root + Iron braid (The First Graft).",
    category: "heartwood",
    spellId: "cast_heartwood",
    costs: [],
    effects: [],
    cooldownMs: 8000,
    prerequisites: [{ actionId: "acquire_braidstone_ring", minExecutions: 1 }],
    logMessage: "Bark hardens where your hands were, alive and unyielding.",
  },
  {
    id: "cast_temper",
    name: "Work Temper",
    description: "Weight plus consumption - blacksmithing. Iron + Ash braid (The First Forging).",
    category: "temper",
    spellId: "cast_temper",
    costs: [],
    effects: [],
    cooldownMs: 9000,
    prerequisites: [{ actionId: "acquire_braidstone_ring", minExecutions: 1 }],
    logMessage: "The metal takes its temper and holds it as promised.",
  },

  // Tier-2 upgrades ×4 - max 5 (compressed from 10), double per-step bonus to preserve total 300% / -2000ms
  {
    id: "upgrade_ash_2",
    name: "Deepen Ash II",
    description: "Ash answers before the heat arrives. Stronger yields, faster recovery. (5 steps, compressed)",
    category: "chapter3",
    costs: [{ resourceId: "motes", amount: 80, scaleFactor: 1.55 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_ash", amount: 0.6 },
      { type: "modify_cooldown_flat", actionId: "cast_ash", amount: -400 },
    ],
    maxExecutions: 5,
    prerequisites: [{ actionId: "cast_ash", minExecutions: 30 }],
  },
  {
    id: "upgrade_root_2",
    name: "Deepen Root II",
    description: "Growth no longer asks permission. Stronger yields, faster recovery. (5 steps, compressed)",
    category: "chapter3",
    costs: [{ resourceId: "motes", amount: 80, scaleFactor: 1.55 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_root", amount: 0.6 },
      { type: "modify_cooldown_flat", actionId: "cast_root", amount: -400 },
    ],
    maxExecutions: 5,
    prerequisites: [{ actionId: "cast_root", minExecutions: 30 }],
  },
  {
    id: "upgrade_hush_2",
    name: "Deepen Hush II",
    description: "Silence obeys at half the asking. Stronger yields, faster recovery. (5 steps, compressed)",
    category: "chapter3",
    costs: [{ resourceId: "motes", amount: 80, scaleFactor: 1.55 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_hush", amount: 0.6 },
      { type: "modify_cooldown_flat", actionId: "cast_hush", amount: -400 },
    ],
    maxExecutions: 5,
    prerequisites: [{ actionId: "cast_hush", minExecutions: 30 }],
  },
  {
    id: "upgrade_iron_2",
    name: "Deepen Iron II",
    description: "Stone listens the first time. Stronger yields, faster recovery. (5 steps, compressed)",
    category: "chapter3",
    costs: [{ resourceId: "motes", amount: 80, scaleFactor: 1.55 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_iron", amount: 0.6 },
      { type: "modify_cooldown_flat", actionId: "cast_iron", amount: -400 },
    ],
    maxExecutions: 5,
    prerequisites: [{ actionId: "cast_iron", minExecutions: 30 }],
  },

  // Journals - three read-actions setting flags journal_one/two/three
  {
    id: "read_journal_one",
    name: "Read: Year 74 Journal I",
    description: "Water-stained Undercroft journal. The first account of the seal being set.",
    category: "chapter3",
    costs: [{ resourceId: "motes", amount: 15 }],
    effects: [{ type: "set_flag", flagId: "journal_one", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [{ taskId: "braid_practice", minExecutions: 1 }],
    logMessage: "Year 74 - 'We sealed it with braid alone so it would answer only to braid.'",
  },
  {
    id: "read_journal_two",
    name: "Read: Year 74 Journal II",
    description: "Second journal. The cost of holding Dormancy against a wound.",
    category: "chapter3",
    costs: [{ resourceId: "motes", amount: 15 }],
    effects: [{ type: "set_flag", flagId: "journal_two", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [{ actionId: "read_journal_one", minExecutions: 1 }],
    logMessage: "Year 74 - 'Things held don't heal. That was the price we did not count.'",
  },
  {
    id: "read_journal_three",
    name: "Read: Year 74 Journal III",
    description: "Third journal. Heartwood offered as answer - living permanence.",
    category: "chapter3",
    costs: [{ resourceId: "motes", amount: 15 }],
    effects: [{ type: "set_flag", flagId: "journal_three", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [{ actionId: "read_journal_two", minExecutions: 1 }],
    logMessage: "Year 74 - 'If it grows and does not break, it may yet hold the Wound.'",
  },
  {
    id: "reconcile_journals",
    name: "Reconcile the Journals",
    description: "Fit the three accounts together. Reward: wider Focus and a Mender's foothold.",
    category: "chapter3",
    costs: [{ resourceId: "motes", amount: 25 }],
    effects: [{ type: "modify_max_resource_flat", resourceId: "focus", amount: 10 }],
    firstCompletionEffects: [{ type: "set_flag", flagId: "mender", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [
      { actionId: "read_journal_one", minExecutions: 1 },
      { actionId: "read_journal_two", minExecutions: 1 },
      { actionId: "read_journal_three", minExecutions: 1 },
    ],
    logMessage: "You close the last page. The Undercroft's purpose steadies in your mind - and your focus with it.",
  },
  {
    id: "acquire_basic_lens",
    name: "Grind the Basic Lens",
    description: "Grind skyglass into a lens. Reveals braid secondary effects faintly.",
    category: "chapter3",
    costs: [
      { resourceId: "skyglass", amount: 4 },
      { resourceId: "motes", amount: 30 },
    ],
    effects: [],
    firstCompletionEffects: [{ type: "add_item", itemId: "basic_lens", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [{ taskId: "braid_practice", minExecutions: 1 }],
    logMessage: "The lens clears. Braid light resolves at the edge of sight.",
  },
  {
    id: "acquire_fine_lens",
    name: "Cut the Fine Lens",
    description: "Clear-cut skyglass. Reveals all braid secondary effects and steadies focus further.",
    category: "chapter3",
    costs: [
      { resourceId: "skyglass", amount: 8 },
      { resourceId: "motes", amount: 60 },
    ],
    effects: [],
    firstCompletionEffects: [{ type: "add_item", itemId: "fine_lens", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [{ actionId: "acquire_basic_lens", minExecutions: 1 }],
    logMessage: "The fine lens catches no light that isn't there - and shows you what is.",
  },
];
