import { TaskConfig } from "../../types";

export const TASKS: TaskConfig[] = [
  {
    id: "advanced_ember_practice",
    name: "Advanced Ember Practice",
    description: "The flame no longer needs coaxing - it answers at pace. Higher Mote yield than basic Ember Practice.",
    category: "braided_casting",
    costPerSecond: [{ resourceId: "focus", amount: 0.45 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 0.9 }],
    xpPerSecond: 8,
    prerequisites: [{ actionId: "upgrade_ash", minExecutions: 5 }],
  },
  {
    id: "advanced_hedge_practice",
    name: "Advanced Hedge Practice",
    description: "Growth comes sharp and deliberate. A steadier, richer residue than hedge basics.",
    category: "braided_casting",
    costPerSecond: [{ resourceId: "focus", amount: 0.45 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 0.9 }],
    xpPerSecond: 8,
    prerequisites: [{ actionId: "upgrade_root", minExecutions: 5 }],
  },
  {
    id: "advanced_stillness_practice",
    name: "Advanced Stillness Practice",
    description: "Silence arrives before the bell is struck. Refined Hush with stronger residue.",
    category: "braided_casting",
    costPerSecond: [{ resourceId: "focus", amount: 0.45 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 0.9 }],
    xpPerSecond: 8,
    prerequisites: [{ actionId: "upgrade_hush", minExecutions: 5 }],
  },
  {
    id: "advanced_stonewatch_practice",
    name: "Advanced Stonewatch Practice",
    description: "Stone hardens at half the invitation. Improved Iron residue over basic Stonewatch.",
    category: "braided_casting",
    costPerSecond: [{ resourceId: "focus", amount: 0.45 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 0.9 }],
    xpPerSecond: 8,
    prerequisites: [{ actionId: "upgrade_iron", minExecutions: 5 }],
  },
  {
    id: "advanced_mote_study",
    name: "Advanced Mote Study",
    description: "Deeper cataloguing - the residue starts looking back. Higher yield than basic Mote Study.",
    category: "braided_casting",
    progressRequired: 30,
    autoRestart: true,
    costPerSecond: [{ resourceId: "focus", amount: 0.5 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 1.2 }],
    xpPerSecond: 9,
    prerequisites: [
      { actionId: "upgrade_ash", minExecutions: 5 },
      { taskId: "mote_study", minExecutions: 3 },
    ],
  },
  {
    id: "braid_practice",
    name: "Braid Practice",
    description: "Weave two Aspects at once. Flooded Undercroft work - the prerequisite for braided casting and Farseer's lenses. Rare skyglass glints in the flooded seams.",
    category: "braided_casting",
    progressRequired: 30,
    autoRestart: true,
    costPerSecond: [{ resourceId: "focus", amount: 0.55 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 1.0 }],
    xpPerSecond: 10,
    prerequisites: [{ actionId: "skyglass_unlock", minExecutions: 1 }],
    completionEffects: [{ type: "add_resource", resourceId: "skyglass", amount: 1, chance: 0.6 }],
  },
];
