import { ActionConfig } from "../../types";

export const ACTIONS: ActionConfig[] = [
  {
    id: "cast_iron",
    name: "Cast: Stonewatch",
    description: "Slightly harden a small object's surface. Introductory Iron casting.",
    category: "iron",
    spellId: "stonewatch",
    costs: [],
    effects: [],
    maxExecutions: 999999,
    cooldownMs: 3000,
    logMessage: "The stone's skin hardens like winter arriving.",
  },
  {
    id: "upgrade_ash",
    name: "Deepen Ash",
    description: "You stop flinching at the heat, and the ash gives more before it settles.",
    category: "chapter2",
    costs: [{ resourceId: "motes", amount: 25, scaleFactor: 1.6 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_ash", amount: 0.25 },
      { type: "modify_cooldown_flat", actionId: "cast_ash", amount: -150 },
    ],
    maxExecutions: 5,
    prerequisites: [{ actionId: "cast_ash", minExecutions: 10 }],
  },
  {
    id: "upgrade_root",
    name: "Deepen Root",
    description: "Growth comes when called now instead of begged.",
    category: "chapter2",
    costs: [{ resourceId: "motes", amount: 25, scaleFactor: 1.6 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_root", amount: 0.25 },
      { type: "modify_cooldown_flat", actionId: "cast_root", amount: -150 },
    ],
    maxExecutions: 5,
    prerequisites: [{ actionId: "cast_root", minExecutions: 10 }],
  },
  {
    id: "upgrade_hush",
    name: "Deepen Hush",
    description: "Silence arrives before you finish asking for it.",
    category: "chapter2",
    costs: [{ resourceId: "motes", amount: 25, scaleFactor: 1.6 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_hush", amount: 0.25 },
      { type: "modify_cooldown_flat", actionId: "cast_hush", amount: -150 },
    ],
    maxExecutions: 5,
    prerequisites: [{ actionId: "cast_hush", minExecutions: 10 }],
  },
  {
    id: "upgrade_iron",
    name: "Deepen Iron",
    description: "Stone remembers your hands and hardens at half the invitation.",
    category: "chapter2",
    costs: [{ resourceId: "motes", amount: 25, scaleFactor: 1.6 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_iron", amount: 0.25 },
      { type: "modify_cooldown_flat", actionId: "cast_iron", amount: -150 },
    ],
    maxExecutions: 5,
    prerequisites: [{ actionId: "cast_iron", minExecutions: 10 }],
  },
  {
    id: "teach_hollow_reach_children",
    name: "Teach Hollow Reach's Children",
    description: "Slowing down for beginners will sharpen every Focus discipline you attempt hereafter.",
    category: "chapter2",
    costs: [],
    effects: [{ type: "modify_yield_pct", resourceId: "focus", amount: 0.25 }],
    firstCompletionEffects: [{ type: "set_flag", flagId: "osrun_choice_made", amount: 1 }],
    maxExecutions: 1,
    exclusiveWith: ["keep_your_lead"],
    logMessage: "\"Then we begin tomorrow,\" Osrun says, and something in the room settles.",
  },
  {
    id: "keep_your_lead",
    name: "Keep Your Lead",
    description: "Your own reserve is thin enough; charity can wait for a quieter season.",
    category: "chapter2",
    costs: [],
    effects: [{ type: "modify_max_resource_pct", resourceId: "mana", amount: 0.10 }],
    firstCompletionEffects: [{ type: "set_flag", flagId: "osrun_choice_made", amount: 1 }],
    maxExecutions: 1,
    exclusiveWith: ["teach_hollow_reach_children"],
    logMessage: "You nod once and keep walking. The children will learn from someone.",
  },
  {
    id: "acquire_conclave_signet",
    name: "Assemble the Conclave Signet",
    description: "The Charm-Maker's Hunt: assemble the Conclave Signet.",
    category: "chapter2",
    costs: [{ resourceId: "motes", amount: 60 }],
    effects: [],
    firstCompletionEffects: [{ type: "add_item", itemId: "conclave_signet", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [{ actionId: "cast_ash", minExecutions: 20 }],
    hideWhenComplete: true,
    logMessage: "The signet is warm, like a stone kept in the sun.",
  },
  {
    id: "settle_into_reach",
    name: "Settle into Reach",
    description: "Take up residence at the Conclave; requisition standard practice gear.",
    category: "chapter2",
    costs: [],
    effects: [],
    firstCompletionEffects: [
      { type: "add_item", itemId: "practice_wand", amount: 1 },
      { type: "add_item", itemId: "wardstone_amulet", amount: 1 },
    ],
    maxExecutions: 1,
    prerequisites: [{ actionId: "widow_cathal_visit", minExecutions: 1 }],
    logMessage: "A borrowed room. A peg for your coat. Yours now.",
  },
  {
    id: "skyglass_unlock",
    name: "Read the Residue",
    description: "Five clean castings, three sessions of study — and the residue starts looking back.",
    category: "endgame",
    costs: [{ resourceId: "motes", amount: 40 }],
    // Engine applies firstCompletionEffects BEFORE effects; capacity must exist
    // before the grant lands or the +20 clamps against baseMax 0 and is lost.
    firstCompletionEffects: [
      { type: "set_max_resource", resourceId: "skyglass", amount: 30 },
      { type: "set_flag", flagId: "skyglass_unlocked", amount: 1 },
    ],
    effects: [{ type: "add_resource", resourceId: "skyglass", amount: 20 }],
    maxExecutions: 1,
    prerequisites: [
      { actionId: "cast_ash", minExecutions: 5 },
      { taskId: "mote_study", minExecutions: 3 },
    ],
    logMessage: "The shard catches light that isn't there.",
  },
  {
    id: "acquire_wardstone_amulet",
    name: "Distill the Wardstone Amulet",
    description: "Fifty loops of practice, distilled into a single worn charm.",
    category: "chapter2",
    costs: [{ resourceId: "motes", amount: 80 }],
    effects: [],
    firstCompletionEffects: [{ type: "add_item", itemId: "wardstone_amulet", amount: 1 }],
    maxExecutions: 1,
    // Proxy gate: "fifty loops of practice" approximated as ten Mote Study sessions (task completions).
    prerequisites: [{ taskId: "mote_study", minExecutions: 10 }],
    hideWhenComplete: true,
  },
];
