import { ActionConfig } from "../../types";

export const ACTIONS: ActionConfig[] = [
  // --- Mastery casts (max 8) for 4 Aspects - tier 3 spells ---
  {
    id: "cast_ash_mastery",
    name: "Mastery: Spendthrift's Flare",
    description: "Convert Mana into a short, powerful burst - mastery Ash (tier 3). Stronger Motes than Coax the Ember.",
    category: "ash",
    spellId: "spendthrifths_flare",
    costs: [],
    effects: [],
    maxExecutions: 8,
    cooldownMs: 8000,
    prerequisites: [{ taskId: "sustain_training", minExecutions: 1 }],
    logMessage: "Spendthrift's Flare answers - bright, costly, entirely yours.",
  },
  {
    id: "cast_root_mastery",
    name: "Mastery: Bramble Snare",
    description: "Rapidly grows entangling vines. Mastery Root (tier 3).",
    category: "root",
    spellId: "bramble_snare",
    costs: [],
    effects: [],
    maxExecutions: 8,
    cooldownMs: 10000,
    prerequisites: [{ taskId: "sustain_training", minExecutions: 1 }],
    logMessage: "Bramble Snare takes - vines knot where you looked.",
  },
  {
    id: "cast_hush_mastery",
    name: "Mastery: Erase",
    description: "Remove a small, specific detail. Mastery Hush (tier 3).",
    category: "hush",
    spellId: "erase",
    costs: [],
    effects: [],
    maxExecutions: 8,
    cooldownMs: 12000,
    prerequisites: [{ taskId: "sustain_training", minExecutions: 1 }],
    logMessage: "Erase takes - the detail is simply not there anymore.",
  },
  {
    id: "cast_iron_mastery",
    name: "Mastery: Leaden Word",
    description: "Sharply increase weight, briefly. Mastery Iron (tier 3).",
    category: "iron",
    spellId: "leaden_word",
    costs: [],
    effects: [],
    maxExecutions: 8,
    cooldownMs: 9000,
    prerequisites: [{ taskId: "sustain_training", minExecutions: 1 }],
    logMessage: "Leaden Word settles - the floor groans and holds.",
  },
  // --- Mastery casts for 4 Braids ---
  {
    id: "cast_smolder_mastery",
    name: "Mastery: Smolder - Ashfall",
    description: "Smolder at mastery - wider, weaker, area-wide. Braid Smolder mastery.",
    category: "smolder",
    spellId: "cast_smolder",
    costs: [],
    effects: [],
    maxExecutions: 8,
    cooldownMs: 6000,
    prerequisites: [{ taskId: "sustain_training", minExecutions: 1 }],
    logMessage: "Smolder spreads thin and silent - ashfall without a sound.",
  },
  {
    id: "cast_dormancy_mastery",
    name: "Mastery: Dormancy - Quiet Bed",
    description: "Dormancy at mastery - extended variant for the wounded. Braid Dormancy mastery.",
    category: "dormancy",
    spellId: "cast_dormancy",
    costs: [],
    effects: [],
    maxExecutions: 8,
    cooldownMs: 7000,
    prerequisites: [{ taskId: "sustain_training", minExecutions: 1 }],
    logMessage: "Dormancy deepens - time holds its breath a little longer.",
  },
  {
    id: "cast_heartwood_mastery",
    name: "Mastery: Heartwood - Livingwall",
    description: "Heartwood at mastery - structural-scale fortification. Braid Heartwood mastery.",
    category: "heartwood",
    spellId: "cast_heartwood",
    costs: [],
    effects: [],
    maxExecutions: 8,
    cooldownMs: 8000,
    prerequisites: [{ taskId: "sustain_training", minExecutions: 1 }],
    logMessage: "Heartwood sets - a wall that breathes and will not break.",
  },
  {
    id: "cast_temper_mastery",
    name: "Mastery: Temper - Second Firing",
    description: "Temper at mastery - refinement pass for equipment. Braid Temper mastery.",
    category: "temper",
    spellId: "cast_temper",
    costs: [],
    effects: [],
    maxExecutions: 8,
    cooldownMs: 9000,
    prerequisites: [{ taskId: "sustain_training", minExecutions: 1 }],
    logMessage: "Temper takes its second firing - the metal remembers better.",
  },

  // --- Tier-3 upgrades x8 (max 15, prereq 60 executions) ---
  {
    id: "upgrade_ash_3",
    name: "Master Ash III",
    description: "Heat obeys before it arrives. Stronger mastery yields, faster recovery.",
    category: "chapter4",
    costs: [{ resourceId: "motes", amount: 150, scaleFactor: 1.55 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_ash_mastery", amount: 0.3 },
      { type: "modify_cooldown_flat", actionId: "cast_ash_mastery", amount: -250 },
    ],
    maxExecutions: 15,
    prerequisites: [{ actionId: "cast_ash", minExecutions: 60 }],
  },
  {
    id: "upgrade_root_3",
    name: "Master Root III",
    description: "Growth no longer asks - it is already there. Stronger yields, faster recovery.",
    category: "chapter4",
    costs: [{ resourceId: "motes", amount: 150, scaleFactor: 1.55 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_root_mastery", amount: 0.3 },
      { type: "modify_cooldown_flat", actionId: "cast_root_mastery", amount: -250 },
    ],
    maxExecutions: 15,
    prerequisites: [{ actionId: "cast_root", minExecutions: 60 }],
  },
  {
    id: "upgrade_hush_3",
    name: "Master Hush III",
    description: "Silence arrives at half the asking. Stronger yields, faster recovery.",
    category: "chapter4",
    costs: [{ resourceId: "motes", amount: 150, scaleFactor: 1.55 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_hush_mastery", amount: 0.3 },
      { type: "modify_cooldown_flat", actionId: "cast_hush_mastery", amount: -250 },
    ],
    maxExecutions: 15,
    prerequisites: [{ actionId: "cast_hush", minExecutions: 60 }],
  },
  {
    id: "upgrade_iron_3",
    name: "Master Iron III",
    description: "Stone listens the first time. Stronger yields, faster recovery.",
    category: "chapter4",
    costs: [{ resourceId: "motes", amount: 150, scaleFactor: 1.55 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_iron_mastery", amount: 0.3 },
      { type: "modify_cooldown_flat", actionId: "cast_iron_mastery", amount: -250 },
    ],
    maxExecutions: 15,
    prerequisites: [{ actionId: "cast_iron", minExecutions: 60 }],
  },
  {
    id: "upgrade_smolder_3",
    name: "Master Smolder III",
    description: "Smolder spreads without announcing itself. Stronger yields, faster recovery.",
    category: "chapter4",
    costs: [{ resourceId: "motes", amount: 160, scaleFactor: 1.55 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_smolder_mastery", amount: 0.3 },
      { type: "modify_cooldown_flat", actionId: "cast_smolder_mastery", amount: -250 },
    ],
    maxExecutions: 15,
    prerequisites: [{ actionId: "cast_smolder", minExecutions: 60 }],
  },
  {
    id: "upgrade_dormancy_3",
    name: "Master Dormancy III",
    description: "Time suspends more faithfully. Stronger yields, faster recovery.",
    category: "chapter4",
    costs: [{ resourceId: "motes", amount: 160, scaleFactor: 1.55 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_dormancy_mastery", amount: 0.3 },
      { type: "modify_cooldown_flat", actionId: "cast_dormancy_mastery", amount: -250 },
    ],
    maxExecutions: 15,
    prerequisites: [{ actionId: "cast_dormancy", minExecutions: 60 }],
  },
  {
    id: "upgrade_heartwood_3",
    name: "Master Heartwood III",
    description: "Bark sets truer, alive and unyielding. Stronger yields, faster recovery.",
    category: "chapter4",
    costs: [{ resourceId: "motes", amount: 160, scaleFactor: 1.55 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_heartwood_mastery", amount: 0.3 },
      { type: "modify_cooldown_flat", actionId: "cast_heartwood_mastery", amount: -250 },
    ],
    maxExecutions: 15,
    prerequisites: [{ actionId: "cast_heartwood", minExecutions: 60 }],
  },
  {
    id: "upgrade_temper_3",
    name: "Master Temper III",
    description: "Metal remembers its second firing forever. Stronger yields, faster recovery.",
    category: "chapter4",
    costs: [{ resourceId: "motes", amount: 160, scaleFactor: 1.55 }],
    effects: [
      { type: "modify_yield_pct", actionId: "cast_temper_mastery", amount: 0.3 },
      { type: "modify_cooldown_flat", actionId: "cast_temper_mastery", amount: -250 },
    ],
    maxExecutions: 15,
    prerequisites: [{ actionId: "cast_temper", minExecutions: 60 }],
  },

  // --- Form-unlock action: single action unlocking 5 forms ---
  {
    id: "casting_forms_awakening",
    name: "Awaken Casting Forms",
    description: "In the ritual hall the forms answer - Method: Ritual/Wild, Duration: Delayed/Sustained, Target: Inward unlock together.",
    category: "forms",
    costs: [
      { resourceId: "motes", amount: 80 },
      { resourceId: "skyglass", amount: 6 },
    ],
    effects: [
      { type: "unlock_casting_form", formId: "method_ritual", amount: 1 },
      { type: "unlock_casting_form", formId: "method_wild", amount: 1 },
      { type: "unlock_casting_form", formId: "duration_delayed", amount: 1 },
      { type: "unlock_casting_form", formId: "duration_sustained", amount: 1 },
      { type: "unlock_casting_form", formId: "target_inward", amount: 1 },
    ],
    firstCompletionEffects: [{ type: "set_flag", flagId: "forms_awakened", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [
      { taskId: "sustain_training", minExecutions: 1 },
      { taskId: "ritual_study", minExecutions: 1 },
      { taskId: "wild_practice", minExecutions: 1 },
    ],
    logMessage: "The forms unlock - Ritual, Wild, Delayed, Sustained, Inward - each a new way to shape intent.",
  },

  // --- Equipment acquisition helpers (Tuners + Steady Hand) ---
  {
    id: "acquire_basic_current_tuner",
    name: "Assemble Basic Current-Tuner",
    description: "Better Motes→Mana conversion. Current-Tuner (basic).",
    category: "chapter4",
    costs: [
      { resourceId: "skyglass", amount: 5 },
      { resourceId: "motes", amount: 40 },
    ],
    effects: [],
    firstCompletionEffects: [{ type: "add_item", itemId: "basic_current_tuner", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [{ taskId: "sustain_training", minExecutions: 1 }],
    logMessage: "The tuner hums with the deep current.",
  },
  {
    id: "acquire_fine_current_tuner",
    name: "Calibrate Fine Current-Tuner",
    description: "+3 Focus and still better conversion. Current-Tuner (fine).",
    category: "chapter4",
    costs: [
      { resourceId: "skyglass", amount: 10 },
      { resourceId: "motes", amount: 80 },
    ],
    effects: [],
    firstCompletionEffects: [{ type: "add_item", itemId: "fine_current_tuner", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [{ actionId: "acquire_basic_current_tuner", minExecutions: 1 }],
    logMessage: "Fine tuning steadies - the current answers more cleanly.",
  },
  {
    id: "acquire_steady_hand",
    name: "Claim the Steady Hand",
    description: "A focus-gear that steadies wild variance. Requires wild practice.",
    category: "chapter4",
    costs: [{ resourceId: "motes", amount: 90 }],
    effects: [],
    firstCompletionEffects: [{ type: "add_item", itemId: "steady_hand", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [{ taskId: "wild_practice", minExecutions: 5 }],
    logMessage: "Your hand steadies - wild casting feels less wild.",
  },
];
