import { TaskConfig } from "../../types";

export const TASKS: TaskConfig[] = [
  {
    id: "ritual_study",
    name: "Ritual Study",
    description: "Slow forms — ritual discipline trades speed for certainty. Chapter IV practice for Method: Ritual.",
    category: "chapter4",
    costPerSecond: [{ resourceId: "focus", amount: 0.6 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 1.1 }],
    xpPerSecond: 10,
    prerequisites: [{ actionId: "acquire_braidstone_ring", minExecutions: 1 }],
  },
  {
    id: "wild_practice",
    name: "Wild Practice",
    description: "Let the wild forms run — cheaper, erratic, alive. Chapter IV practice for Method: Wild.",
    category: "chapter4",
    costPerSecond: [{ resourceId: "focus", amount: 0.55 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 1.25 }],
    xpPerSecond: 10,
    prerequisites: [{ actionId: "acquire_braidstone_ring", minExecutions: 1 }],
  },
  {
    id: "sustain_training",
    name: "Sustain Training",
    description: "Hold a working past its instant — learn sustained drain. Unlocks Current-Tuner and mastery casts.",
    category: "chapter4",
    costPerSecond: [{ resourceId: "focus", amount: 0.75 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 1.0 }],
    xpPerSecond: 11,
    prerequisites: [{ actionId: "acquire_braidstone_ring", minExecutions: 1 }],
  },
  {
    id: "mastery_ember_practice",
    name: "Mastery Ember Practice",
    description: "Flame answers before the word is finished. Mastery-tier Ash — higher yield than Advanced Ember.",
    category: "chapter4",
    costPerSecond: [{ resourceId: "focus", amount: 0.6 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 1.5 }],
    xpPerSecond: 12,
    prerequisites: [
      { actionId: "upgrade_ash_2", minExecutions: 1 },
      { taskId: "sustain_training", minExecutions: 1 },
    ],
  },
  {
    id: "mastery_hedge_practice",
    name: "Mastery Hedge Practice",
    description: "Growth comes sharp and deliberate, then holds. Mastery-tier Root — richer residue.",
    category: "chapter4",
    costPerSecond: [{ resourceId: "focus", amount: 0.6 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 1.5 }],
    xpPerSecond: 12,
    prerequisites: [
      { actionId: "upgrade_root_2", minExecutions: 1 },
      { taskId: "sustain_training", minExecutions: 1 },
    ],
  },
  {
    id: "mastery_stillness_practice",
    name: "Mastery Stillness Practice",
    description: "Silence arrives before the bell is struck and stays. Mastery-tier Hush — stronger residue.",
    category: "chapter4",
    costPerSecond: [{ resourceId: "focus", amount: 0.6 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 1.5 }],
    xpPerSecond: 12,
    prerequisites: [
      { actionId: "upgrade_hush_2", minExecutions: 1 },
      { taskId: "sustain_training", minExecutions: 1 },
    ],
  },
  {
    id: "mastery_stonewatch_practice",
    name: "Mastery Stonewatch Practice",
    description: "Stone hardens at half the invitation and remembers. Mastery-tier Iron — improved residue.",
    category: "chapter4",
    costPerSecond: [{ resourceId: "focus", amount: 0.6 }],
    effectsPerSecond: [{ type: "add_resource", resourceId: "motes", amount: 1.5 }],
    xpPerSecond: 12,
    prerequisites: [
      { actionId: "upgrade_iron_2", minExecutions: 1 },
      { taskId: "sustain_training", minExecutions: 1 },
    ],
  },
];
