import { ActionConfig } from "../../types";

export const ACTIONS: ActionConfig[] = [
  // --- WORLD 5 ---
  {
    id: "note_chimney_primer",
    name: "Notebook: Chimney Primer",
    description: "World - soot-smudged primer behind Millhollow's chimney. Ash basics from before Year 70.",
    category: "notebook",
    costs: [{ resourceId: "motes", amount: 6 }],
    effects: [{ type: "set_flag", flagId: "note_chimney_primer", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_max_resource_flat", resourceId: "focus", amount: 2 }],
    maxExecutions: 1,
    prerequisites: [{ taskId: "catch_your_breath", minExecutions: 3 }],
    logMessage: "Chimney Primer - 'The first flame is the one you already have.' +2 Focus.",
  },
  {
    id: "note_patient_well",
    name: "Notebook: Patient Well",
    description: "World - the village well that never ran dry, even in Cinderfall. Root remembers water.",
    category: "notebook",
    costs: [{ resourceId: "motes", amount: 8 }],
    effects: [{ type: "set_flag", flagId: "note_patient_well", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_max_resource_flat", resourceId: "focus", amount: 2 }],
    maxExecutions: 1,
    prerequisites: [{ actionId: "widow_cathal_visit", minExecutions: 1 }],
    logMessage: "Patient Well - the stone remembers being laid, course by course.",
  },
  {
    id: "note_unwitnessed_garden",
    name: "Notebook: Unwitnessed Garden",
    description: "World - a garden no one claims to tend, yet never overgrows. Hush laid over Root.",
    category: "notebook",
    costs: [{ resourceId: "motes", amount: 10 }],
    effects: [{ type: "set_flag", flagId: "note_unwitnessed_garden", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_max_resource_flat", resourceId: "focus", amount: 2 }],
    maxExecutions: 1,
    prerequisites: [
      { actionId: "cast_hush", minExecutions: 5 },
      { taskId: "library_duty", minExecutions: 1 },
    ],
    logMessage: "Unwitnessed Garden - absence and growth holding each other still.",
  },
  {
    id: "note_missing_verse",
    name: "Notebook: Missing Verse",
    description: "World - a hymnal verse excised cleanly, paper fibers uncut. Erase, carefully done.",
    category: "notebook",
    costs: [{ resourceId: "motes", amount: 12 }],
    effects: [{ type: "set_flag", flagId: "note_missing_verse", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_max_resource_flat", resourceId: "focus", amount: 2 }],
    maxExecutions: 1,
    prerequisites: [{ taskId: "library_duty", minExecutions: 1 }],
    logMessage: "Missing Verse - someone removed a word so precisely the page forgot it.",
  },
  {
    id: "note_widow_cathals_box",
    name: "Notebook: Widow Cathal's Box",
    description: "World - Cathal's locked ashwood box. Opens only after the deep current answers.",
    category: "notebook",
    costs: [
      { resourceId: "motes", amount: 25 },
      { resourceId: "skyglass", amount: 3 },
    ],
    effects: [{ type: "set_flag", flagId: "note_widow_cathals_box", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_max_resource_flat", resourceId: "focus", amount: 4 }],
    maxExecutions: 1,
    prerequisites: [
      { actionId: "widow_cathal_visit", minExecutions: 1 },
      { actionId: "unlock_deep_current", minExecutions: 1 },
    ],
    logMessage: "Cathal's Box clicks open - ashwork inside, warm as a promise kept.",
  },

  // --- STUDY 4 (gated by library_duty) ---
  {
    id: "note_ashen_history",
    name: "Notebook: Ashen History",
    description: "Study - Conclave annals: Ash before the Sundering, when consumption was trade, not weapon.",
    category: "notebook",
    costs: [{ resourceId: "motes", amount: 10 }],
    effects: [{ type: "set_flag", flagId: "note_ashen_history", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_max_resource_flat", resourceId: "focus", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [{ taskId: "library_duty", minExecutions: 2 }],
    logMessage: "Ashen History - chronicles of fire that asked permission.",
  },
  {
    id: "note_root_history",
    name: "Notebook: Root History",
    description: "Study - Root histories: how Millhollow hedges were grown, not planted.",
    category: "notebook",
    costs: [{ resourceId: "motes", amount: 10 }],
    effects: [{ type: "set_flag", flagId: "note_root_history", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_max_resource_flat", resourceId: "focus", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [{ taskId: "library_duty", minExecutions: 3 }],
    logMessage: "Root History - 'We did not build the hedge. We convinced it.'",
  },
  {
    id: "note_hush_history",
    name: "Notebook: Hush History",
    description: "Study - Hush marginalia: the year silence was first laid over a battlefield and held.",
    category: "notebook",
    costs: [{ resourceId: "motes", amount: 10 }],
    effects: [{ type: "set_flag", flagId: "note_hush_history", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_max_resource_flat", resourceId: "focus", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [{ taskId: "library_duty", minExecutions: 4 }],
    logMessage: "Hush History - a ledger of things made unremembered on purpose.",
  },
  {
    id: "note_iron_history",
    name: "Notebook: Iron History",
    description: "Study - Iron ledgers: Anchors first used to hold Hollow Reach against the scar's pull.",
    category: "notebook",
    costs: [{ resourceId: "motes", amount: 10 }],
    effects: [{ type: "set_flag", flagId: "note_iron_history", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_max_resource_flat", resourceId: "focus", amount: 1 }],
    maxExecutions: 1,
    prerequisites: [{ taskId: "library_duty", minExecutions: 5 }],
    logMessage: "Iron History - 'We made the ground remember to stay.'",
  },

  // --- CRAFT 4 ---
  {
    id: "note_charm_makers_hunt",
    name: "Notebook: Charm-Maker's Hunt",
    description: "Craft - hunt the dispersed tools of the old charm-maker. Traces remain in skyglass.",
    category: "notebook",
    costs: [
      { resourceId: "motes", amount: 18 },
      { resourceId: "skyglass", amount: 2 },
    ],
    effects: [{ type: "set_flag", flagId: "note_charm_makers_hunt", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_max_resource_flat", resourceId: "focus", amount: 3 }],
    maxExecutions: 1,
    prerequisites: [
      { actionId: "cast_ash", minExecutions: 15 },
      { actionId: "skyglass_unlock", minExecutions: 1 },
    ],
    logMessage: "Charm-Maker's Hunt - brass filings, a cooled crucible, a note: 'Again.'",
  },
  {
    id: "note_braidstone_hunt",
    name: "Notebook: Braidstone Hunt",
    description: "Craft - survey the Undercroft for braidstone seams. Requires braid practice to read.",
    category: "notebook",
    costs: [
      { resourceId: "motes", amount: 22 },
      { resourceId: "skyglass", amount: 3 },
    ],
    effects: [{ type: "set_flag", flagId: "note_braidstone_hunt", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_max_resource_flat", resourceId: "mana", amount: 10 }],
    maxExecutions: 1,
    prerequisites: [
      { taskId: "braid_practice", minExecutions: 3 },
      { actionId: "acquire_braidstone_ring", minExecutions: 1 },
    ],
    logMessage: "Braidstone Hunt - a seam glints with two colors at once. You mark it.",
  },
  {
    id: "note_farseers_commission",
    name: "Notebook: Farseer's Commission",
    description: "Craft - commission a farseer's lens properly. Skyglass, ground to sight.",
    category: "notebook",
    costs: [
      { resourceId: "motes", amount: 30 },
      { resourceId: "skyglass", amount: 4 },
    ],
    effects: [{ type: "set_flag", flagId: "note_farseers_commission", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_max_resource_flat", resourceId: "focus", amount: 3 }],
    maxExecutions: 1,
    prerequisites: [{ actionId: "acquire_basic_lens", minExecutions: 1 }],
    logMessage: "Farseer's Commission - the grinder sings against skyglass until it shows true.",
  },
  {
    id: "note_deryns_old_kit",
    name: "Notebook: Deryn's Old Kit",
    description: "Craft - Deryn's abandoned field kit. Practical, incomplete, stubbornly useful.",
    category: "notebook",
    costs: [{ resourceId: "motes", amount: 16 }],
    effects: [{ type: "set_flag", flagId: "note_deryns_old_kit", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_max_resource_flat", resourceId: "focus", amount: 2 }],
    maxExecutions: 1,
    prerequisites: [{ taskId: "mote_study", minExecutions: 5 }],
    logMessage: "Deryn's Old Kit - canvas, vials, a whetstone worn to a smile.",
  },

  // --- FAILURE 4 (deliberate misfires; engine lacks failedCastings prereq so gate via high cast counts) ---
  {
    id: "note_successful_misfire",
    name: "Notebook: Successful Misfire",
    description: "Failure - a clean-looking miscast that taught more than the success. Requires broad casting experience.",
    category: "notebook",
    costs: [{ resourceId: "motes", amount: 14 }],
    effects: [{ type: "set_flag", flagId: "note_successful_misfire", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_max_resource_flat", resourceId: "focus", amount: 3 }],
    maxExecutions: 1,
    prerequisites: [
      { actionId: "cast_ash", minExecutions: 25 },
      { actionId: "cast_root", minExecutions: 15 },
      { taskId: "sustain_training", minExecutions: 1 },
    ],
    logMessage: "Successful Misfire - 'It failed well. That is not nothing.'",
  },
  {
    id: "note_lesson_of_ash",
    name: "Notebook: Lesson of Ash",
    description: "Failure - Ash overshoots at low Focus. Learn the shape of too much.",
    category: "notebook",
    costs: [{ resourceId: "motes", amount: 18 }],
    effects: [{ type: "set_flag", flagId: "note_lesson_of_ash", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_failure_chance", amount: -0.02 }],
    maxExecutions: 1,
    prerequisites: [
      { actionId: "cast_ash", minExecutions: 35 },
      { actionId: "cast_ash_mastery", minExecutions: 1 },
    ],
    logMessage: "Lesson of Ash - the bonfire teaches what the candle would not.",
  },
  {
    id: "note_lesson_of_iron",
    name: "Notebook: Lesson of Iron",
    description: "Failure - Iron fixes the wrong thing, permanently. Learn where not to set.",
    category: "notebook",
    costs: [{ resourceId: "motes", amount: 18 }],
    effects: [{ type: "set_flag", flagId: "note_lesson_of_iron", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_failure_chance", amount: -0.02 }],
    maxExecutions: 1,
    prerequisites: [
      { actionId: "cast_iron", minExecutions: 35 },
      { actionId: "cast_iron_mastery", minExecutions: 1 },
    ],
    logMessage: "Lesson of Iron - what settles wrong does not apologize.",
  },
  {
    id: "note_lesson_of_hush",
    name: "Notebook: Lesson of Hush",
    description: "Failure - Hush silences the wrong thing, including the caster. Learn the edge.",
    category: "notebook",
    costs: [{ resourceId: "motes", amount: 18 }],
    effects: [{ type: "set_flag", flagId: "note_lesson_of_hush", amount: 1 }],
    firstCompletionEffects: [{ type: "modify_failure_chance", amount: -0.02 }],
    maxExecutions: 1,
    prerequisites: [
      { actionId: "cast_hush", minExecutions: 35 },
      { actionId: "cast_hush_mastery", minExecutions: 1 },
    ],
    logMessage: "Lesson of Hush - the bell you meant to quiet was not the one that went silent.",
  },
];
